# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dev_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_id', models.CharField(default='Null', max_length=15)),
                ('machine_name', models.CharField(default='Null', max_length=40)),
                ('mac_addr', models.CharField(max_length=255, unique=True)),
                ('int_name', models.CharField(default='Null', max_length=20)),
                ('int_type', models.CharField(default='Null', max_length=255)),
                ('pwrstatus', models.CharField(default='Null', max_length=10)),
                ('cpu_cores', models.IntegerField()),
                ('cpu_type', models.CharField(default='Null', max_length=255)),
                ('ram', models.IntegerField(default=0)),
                ('storage', models.FloatField(default=10.7)),
                ('ip_addr', models.GenericIPAddressField(default='0.0.0.0')),
            ],
        ),
        migrations.CreateModel(
            name='maas_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_id', models.CharField(default='Null', max_length=15)),
                ('machine_name', models.CharField(default='Null', max_length=40)),
                ('machine_status', models.CharField(default='Null', max_length=40)),
                ('time_detected', models.CharField(default='Null', max_length=30)),
            ],
        ),
    ]
